"""
Single source of truth for nginx domain vhost generation.

Both ssl_deploy.py and the nodejs plugin call render_domain_vhost().
It queries the current DB state to decide whether the domain should be
a reverse proxy (nodejs app assigned) or a static file server.
"""
from __future__ import annotations

MARKER = "# Generated by HostPanel"
_LOG_DIR = "/opt/hostpanel/plugins/nginx/logs"


def render_domain_vhost(domain: str, linux_user: str, cert_path: str = "", key_path: str = "") -> str:
    port = _nodejs_port(domain)
    doc_root = f"/home/{linux_user}/public_html"
    if port:
        return _proxy(domain, port, cert_path, key_path, _nodejs_routes(domain))
    return _static(domain, doc_root, cert_path, key_path)


_LEGACY_MARKERS = ("# Managed by hostpanel-nodejs", "# Restored by hostpanel-nodejs")


def is_hostpanel_vhost(content: str) -> bool:
    if MARKER in content:
        return True
    return any(m in content for m in _LEGACY_MARKERS)


# ── internal helpers ──────────────────────────────────────────────────────────

def _nodejs_port(domain: str):
    try:
        from hostpanel_nodejs.store import get_app_by_domain
        app = get_app_by_domain(domain)
        return int(app["port"]) if app else None
    except Exception:
        return None


# Anything outside this shape never reaches the config — nginx directive
# injection through a route path ("/x/ { ... }") must be impossible here
# regardless of what the plugin stored.
_ROUTE_PATH_RE = None


def _safe_routes(routes: list) -> list:
    import re
    global _ROUTE_PATH_RE
    if _ROUTE_PATH_RE is None:
        _ROUTE_PATH_RE = re.compile(r"^(/[A-Za-z0-9._-]+)+$")
    safe = []
    for route in routes:
        try:
            path = str(route["path"])
            port = int(route["port"])
        except Exception:
            continue
        if not _ROUTE_PATH_RE.fullmatch(path) or ".." in path or len(path) > 128:
            continue
        if not (1 <= port <= 65535):
            continue
        safe.append({"path": path, "port": port, "strip_prefix": bool(route.get("strip_prefix", True))})
    return safe


def _nodejs_routes(domain: str) -> list:
    """Custom per-app reverse-proxy routes declared in the nodejs plugin.
    Older plugin versions don't have the accessor — treat as no routes. The
    plugin validates on write, but this renderer emits privileged config, so
    it re-validates on read and drops anything off-shape."""
    try:
        from hostpanel_nodejs.store import get_routes_by_domain
        return _safe_routes(get_routes_by_domain(domain) or [])
    except Exception:
        return []


_PROXY_HEADERS = """        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";"""


def _proxy(domain: str, port: int, cert_path: str, key_path: str, routes: list = ()) -> str:
    # Custom routes go before location / so their prefixes win; a trailing
    # slash on proxy_pass makes nginx strip the matched prefix.
    route_blocks = ""
    for route in routes:
        strip = "/" if route.get("strip_prefix", True) else ""
        route_blocks += f"""    location {route['path']}/ {{
        proxy_pass http://127.0.0.1:{int(route['port'])}{strip};
{_PROXY_HEADERS}
    }}

"""

    proxy_block = f"""{route_blocks}    location / {{
        proxy_pass http://127.0.0.1:{port};
{_PROXY_HEADERS}
    }}"""

    if cert_path:
        return f"""{MARKER}
server {{
    listen 80;
    server_name {domain} www.{domain};

    location ^~ /.well-known/acme-challenge/ {{
        root /opt/hostpanel/acme;
        default_type "text/plain";
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    server_name {domain} www.{domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    add_header Strict-Transport-Security "max-age=31536000" always;

{proxy_block}
}}
"""
    return f"""{MARKER}
server {{
    listen 80;
    server_name {domain} www.{domain};

{proxy_block}
}}
"""


def _static(domain: str, doc_root: str, cert_path: str, key_path: str) -> str:
    if cert_path:
        return f"""{MARKER}
server {{
    listen 80;
    server_name {domain} www.{domain};

    location ^~ /.well-known/acme-challenge/ {{
        root {doc_root};
        default_type "text/plain";
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    server_name {domain} www.{domain};
    root {doc_root};
    index index.php index.html index.htm;

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    add_header Strict-Transport-Security "max-age=31536000" always;

    access_log {_LOG_DIR}/{domain}.access.log;
    error_log  {_LOG_DIR}/{domain}.error.log;

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""
    return f"""{MARKER}
server {{
    listen 80;
    server_name {domain} www.{domain};
    root {doc_root};
    index index.php index.html index.htm;

    access_log {_LOG_DIR}/{domain}.access.log;
    error_log  {_LOG_DIR}/{domain}.error.log;

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""
